### ISSUE TITLE
Add option for max length prefix size

### ISSUE THREAD

**Issue by Minikloon** [mstefarov/fNbt#24]
MCPE packet 0x38 originating from the client sets a Minecraft block metadata by sending its nbt.

Clients may fool servers and cause performance issues by spamming max size length prefixes in that nbt. fNbt will allocate these massive arrays and this may cause OutOfMemoryExceptions.

Affected tags:
- Byte array
- String
- List
- Int array

I suggest adding a MaxBufferSize property to NbtBinaryReader with a convenience proxy in NbtFile.

**Comment by fragmer** [comment]
Hmm this is an interesting problem that I have not considered. Thanks for bringing it up. I will prioritize this for the next release.

**Comment by mstefarov** [comment]
Mostly fixed in [v1.1.1](https://github.com/mstefarov/fNbt/releases/tag/v1.1.1), but in a different way than you suggested. When fNbt reads from a seekable stream, which is what the packet case here uses, it now rejects any declared length that cannot fit in the remaining input. The check runs before anything is allocated, so a few bytes claiming a 2 GB array simply throw a catchable EndOfStreamException.

This solves the reported problem, so I'm closing the issue. The check cannot cover non-seekable streams, where the remaining size is unknown. I might add a configurable limit in the next version if the check does not kill performance.

Thanks for the report, and sorry it took a while.
